name: CD
on:
  push:
    branches: [main]

env:
  AZURE_CONTAINER_REGISTRY: acr_name
  CONTAINER_APP_NAME: ca_name
  RESOURCE_GROUP: rg_name

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4 
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      
      - name: Build and push container image into ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # Tag container image with the commit hash
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ CONTAINER_APP_NAME }}:${{ github.sha }}
          labels: DOCKERFILE_HERE
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploy To Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ CONTAINER_APP_NAME }}:${{ github.sha }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          